mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import IndexView, UserCreateView, UserCreateDoneTV

from bookmark.views import BookmarkLV, BookmarkDV
from bookmark_youtube.views import BookmarkYoutubeLV, BookmarkYoutubeDV, BookmarkYoutubeCV
from blog.views import PostLV, PostDV, PostCV
from bookmarkIndex.views import BookmarkIndexView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name = 'index'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('bookmark/', BookmarkIndexView.as_view(), name='bookmark_index'),
    path('bookmark/regular/', BookmarkLV.as_view(), name='bookmark_regular_index'),
    path('bookmark/regular/<int:pk>/', BookmarkDV.as_view(), name = 'detail'),
    path('bookmark/youtube/', BookmarkYoutubeLV.as_view(), name = 'bookmarkYoutube_index'),
    path('bookmark/youtube/<int:pk>/', BookmarkYoutubeDV.as_view(), name = 'bookmarkYoutube_detail'),
    path('bookmark/youtube/add/', BookmarkYoutubeCV.as_view(), name="bookmarkYoutube_add"),
    path('blog/', PostLV.as_view(), name='blog_index'),
    path('blog/<int:pk>/', PostDV.as_view(), name='blog_detail'),
    path('blog/add/', PostCV.as_view(), name="blog_add"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(blank=True)
    description = models.CharField('Description',
                                   max_length=100, blank=True,
                                   help_text='simple description')
    create_date = models.DateTimeField('Date Created', auto_now_add=True,
                                       blank=True, null=True)
    modify_date = models.DateTimeField('Date Modified', auto_now=True,
                                       blank=True, null=True)

    def __str__(self):
        return self.title

bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank= True, null = True)
    url = models.URLField('url', unique=True)
    create_date = models.DateTimeField('Create Date', auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.title

bookmarkIndex/models.py
from django.db import models

# Create your models here.

bookmark_youtube/models.py
from django.db import models

# Create your models here.

class BookmarkYoutube(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    create_date = models.DateTimeField('Date Created', auto_now_add=True,
                                       blank=True, null=True)
    modify_date = models.DateTimeField('Date Modified', auto_now=True,
                                       blank=True, null=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from blog.models import Post
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.

class PostLV(ListView):
    model = Post

class PostDV(DetailView):
    model = Post

class PostCV(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'image', 'description']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog_index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCV,self).form_valid(form)

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

bookmarkIndex/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
# Create your views here.

class BookmarkIndexView(TemplateView):
    template_name = 'bookmark_index.html'

bookmark_youtube/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark_youtube.models import BookmarkYoutube
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.

class BookmarkYoutubeLV(ListView):
    model = BookmarkYoutube

class BookmarkYoutubeDV(DetailView):
    model = BookmarkYoutube

class BookmarkYoutubeCV(LoginRequiredMixin, CreateView):
    model = BookmarkYoutube
    fields = ['title', 'url']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('bookmarkYoutube_index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkYoutubeCV,self).form_valid(form)

mysite/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class IndexView(TemplateView):
    template_name = 'index.html'

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>Post List</title>
    <script>
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://dm402samplepage.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% load static %}
    <style>
        .logo {
            flex: 1;
        }
        .functionTexts{
            color: lightgrey;

        }
    </style>
</head>
<body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header" style="text-align: center">
                <a href="{% url 'index' %}">
                    <img class = "navbar-brand" src="../../media/dlab_logo_white.png">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a href="{% url 'bookmark_index' %}">BOOKMARK</a></li>
                <li><a href="{% url 'blog_index' %}">BLOG</a></li>
            </ul>

            {% if user.is_active %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'logout' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Out</button>
                </a>
                <a href="{% url 'password_change' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Change Password</button>
                </a>
            </div>
            <p class="navbar-text">디랩의 자랑, {{ user.get_username }}님을 환영합니다.</p>

            {% else %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'register' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Up</button>
                </a>
                <a href="{% url 'login' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Login</button>
                </a>
            </div>
            <p class="navbar-text">some text</p>
            {% endif %}
        </div>
    </nav>

<br><br>
    <div class="row">
        <div class = "col-sm-2"></div>
        <div class = "col-sm-8 logo">

            <div>
                <img src = "../../media/logo.jpg">
            </div>
             <div class="thumbnail">
                 <h5>{{ object.title }}</h5>
                 <img src = "{{ object.image.url }}">
                 <p>{{ object.description }}</p>
                 <p class="functionTexts">Post Created: {{object.create_date}}</p>
                 <p class="functionTexts">Last modified: {{object.modify_date}}</p>
                 <div id="disqus_thread"></div>
            </div>
        </div>
        <div class = "col-sm-2"></div>
    </div>

</body>
</html>

templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% load static %}
    <style>
        .logo {
            flex: 1;
        }
        .functionTexts{
            color: lightgrey;

        }
        #id_title{
        width: 80%;
        border: none;
        border-bottom: 2px solid navy;
        }
        #id_description{
        width: 80%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        }

    </style>
</head>
<body>


{% load static %}

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header" style="text-align: center">
            <a href="{% url 'index' %}">
                <img class="navbar-brand" src="../../media/dlab_logo_white.png">
            </a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a href="{% url 'bookmark_index' %}">BOOKMARK</a></li>
            <li><a href="{% url 'blog_index' %}">BLOG</a></li>
        </ul>

        {% if user.is_active %}

        <div class="navbar-nav" style="padding-top: 10px;">
            <a href="{% url 'logout' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Sign Out</button>
            </a>
            <a href="{% url 'password_change' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Change Password</button>
            </a>
        </div>
        <p class="navbar-text">디랩의 자랑, {{ user.get_username }}님을 환영합니다.</p>

        {% else %}

        <div class="navbar-nav" style="padding-top: 10px;">
            <a href="{% url 'register' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Sign Up</button>
            </a>
            <a href="{% url 'login' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Login</button>
            </a>
        </div>
        <p class="navbar-text">some text</p>
        {% endif %}
    </div>
</nav>


<br><br>
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 logo">

        <div>
            <img src="../../media/logo.jpg">
        </div>
        <div class="thumbnail">
            <h4>블로그에 새로운 게시글을 올립니다.</h4>
            <p>아래 정보를 정확하게 입력해주세요.</p>
            <br><br>

            <form class="card-text top-buffer" action="." method="post" enctype='multipart/form-data'>
                {% csrf_token %}

                <fieldset class="aligned">
                    <br>
                    <div class="form-group">
                        제목: {{ form.title }}
                    </div>
                    <br>
                    <div class="form-group">
                        이미지: <br><br>{{ form.image }}
                    </div>
                    <br>
                    <div class="form-group">
                        설명: {{ form.description }}
                    </div>
                    <br>
                    <button class="btn btn-primary" type="submit">업로드</button>
                    <br>
                    <br>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="col-sm-2"></div>
</div>


</body>
</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% load static %}
    <style>
        .logo {
            flex: 1;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header" style="text-align: center">
                <a href="{% url 'index' %}">
                    <img class = "navbar-brand" src="../../media/dlab_logo_white.png">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a href="{% url 'bookmark_index' %}">BOOKMARK</a></li>
                <li><a href="{% url 'blog_index' %}">BLOG</a></li>
            </ul>

            {% if user.is_active %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'logout' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Out</button>
                </a>
                <a href="{% url 'password_change' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Change Password</button>
                </a>
            </div>
            <p class="navbar-text">디랩의 자랑, {{ user.get_username }}님을 환영합니다.</p>

            {% else %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'register' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Up</button>
                </a>
                <a href="{% url 'login' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Login</button>
                </a>
            </div>
            <p class="navbar-text">some text</p>
            {% endif %}
        </div>
    </nav>

<br><br>
    <div class="row">
        <div class = "col-sm-4"></div>
        <div class = "col-sm-4 logo">

            <div>
                <img src = "../media/logo.jpg">
                <br>
                <a href="{% url 'blog_add' %}">
                    <button type="button" class="btn btn-info">Add a new post</button>
                </a>
                <br>
                <br>
            </div>
            {% for post in object_list %}
             <div class="thumbnail">
                <h5>{{ post.title }}</h5>
                 <a href="{% url 'blog_detail' post.id %}">
                     {% if post.image.url != null %}
                        <img src = "{{ post.image.url }}" onerror="this.onerror=null; this.src='../media/imageerror.png'">
                     {% else %}
                        <img src  ="../media/imageerror.png">
                     {% endif %}
                 </a>
                <p>{{ post.description }}</p>
            </div>
            {% endfor %}
        </div>
    </div>


</body>
</html>

templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <style>
        html {
            background: url(../../../media/frame.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        h1 {

            position: absolute;
            font-family: 'Bebas Neue', cursive;
            top: 35%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: black;
            font-size: 50px;
        }
        .container{
            position: absolute;
            top: 60%;
            left: 48%;
            transform: translate(-50%, -50%);
        }

        li {
            position: relative;
            list-style-type: none;
            font-family: 'Roboto Mono', monospace;
            color: black;
            font-size: 18px;
        }
    </style>
</head>
<body>

    <h1>{{ object.title }}</h1>
    <div class="container">
        <ul>
            <li>URL: {{object.url}}</li>
            <li>Create Date: {{ object.create_date }}</li>
        </ul>
    </div>

</body>
</html>

templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>D.LAB X Django</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
    <style>
        html {
            background: url("https://cdn.pixabay.com/photo/2015/06/08/15/11/typewriter-801921_960_720.jpg") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        h1 {

            position: absolute;
            font-family: 'Parisienne', cursive;
            top: 35%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: black;
            font-size: 50px;
        }
        .container1{
            position: absolute;
            top: 60%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        #content li {
            position: relative;
            list-style-type: none;
            font-family: 'Roboto Mono', monospace;
            color: black;
            font-size: 35px;
            text-decoration: none;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header" style="text-align: center">
                <a href="{% url 'index' %}">
                    <img class = "navbar-brand" src="../../media/dlab_logo_white.png">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a href="{% url 'bookmark_index' %}">BOOKMARK</a></li>
                <li><a href="{% url 'blog_index' %}">BLOG</a></li>
            </ul>

            {% if user.is_active %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'logout' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Out</button>
                </a>
                <a href="{% url 'password_change' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Change Password</button>
                </a>
            </div>
            <p class="navbar-text">디랩의 자랑, {{ user.get_username }}님을 환영합니다.</p>

            {% else %}

            <div class = "navbar-nav" style="padding-top: 10px;">
                <a href="{% url 'register' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Sign Up</button>
                </a>
                <a href="{% url 'login' %}">
                    <button class="btn btn-sm btn-outline-secondary" type="button">Login</button>
                </a>
            </div>
            <p class="navbar-text">some text</p>
            {% endif %}
        </div>
    </nav>

    <div id = "content">
        <h1>Bookmark List</h1>
        <div class="container1">
            <ul>
                {% for bookmark in object_list %}
                <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }}</a></li><br>
                {% endfor %}
            </ul>
        </div>
    </div>

</body>
</html>

templates/bookmark_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


</head>
<style>
</style>
<body>


<br>
<div class="container p-3 my-3 bg-dark text-white">
    <h1>Bookmark App Options:</h1>
</div>

<br><br><br>
<div class = "row">
    <div class="col-sm-6 left">
      <div class="thumbnail">
        <a href="{% url 'bookmark_regular_index' %}"><img src="https://cdn.pixabay.com/photo/2015/06/08/15/11/typewriter-801921_960_720.jpg" alt="Regular Bookmark"></a>
        <h2>북마크 앱</h2>
        <h5>브라우저의 즐겨찾기/북마크 기능과 동일합니다.</h5>
      </div>
    </div>

    <div class="col-sm-6 right">
      <div class="thumbnail">
        <a href="{% url 'bookmarkYoutube_index' %}"><img src="../../media/youtube-2617510_1920.jpg" alt="Youtube Bookmark"></a>
        <h2>유튜브 북마크 앱</h2>
        <h5>내가 좋아하는 유튜브 동영상들을 저장하고 재생하는 웹페이지입니다.</h5>
      </div>
    </div>

</body>
</html>

templates/bookmark_youtube/bookmarkyoutube_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <style>
        #content{
            text-align: center;
            font-size: 30px;
            font-family: 'Do Hyeon', sans-serif;
            width: 900px;
            height: 900px;
            margin: auto;
        }
        ul{
            list-style:none;

        }
        li{
            width: 900px;
            margin: auto;
            margin-bottom: 30px;
            text-align: left;
        }
        #title{
            font-family: 'Do Hyeon', sans-serif;
            font-size: 100px;
            color: red;
        }
        .small{
            font-size: 20px;
            color: gray;
        }
        a{
            text-decoration: none;
            color: dimgray;
        }
        li:hover{
            background-color: rgba(255,20,147,0.1);
        }
        iframe{
            width: 900px;
            height: 506px;
        }
    </style>
</head>
<body>

<div id="content">

    <h1 id="title">{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
        <li>Create Date: {{ object.create_date }}</li>
    </ul>
    <iframe src="{{object.url}}"></iframe>


</div>


</body>
</html>

templates/bookmark_youtube/bookmarkyoutube_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% load static %}
    <style>
        .logo {
            flex: 1;
        }
        .functionTexts{
            color: lightgrey;

        }
        #id_title{
        width: 80%;
        border: none;
        border-bottom: 2px solid navy;
        }
        #id_description, #id_url{
        width: 80%;
        padding: 12px 20px;
        margin: 8px 0;
        box-sizing: border-box;
        }
        .formCard{
            padding: 12px 20px;
            margin: 100px 0;
        }
        .codeHighlight{
            color: #E01E5A;
        }

    </style>
</head>
<body>


{% load static %}

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header" style="text-align: center">
            <a href="{% url 'index' %}">
                <img class="navbar-brand" src="../../../media/dlab_logo_white.png">
            </a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a href="{% url 'bookmark_index' %}">BOOKMARK</a></li>
            <li><a href="{% url 'blog_index' %}">BLOG</a></li>
        </ul>

        {% if user.is_active %}

        <div class="navbar-nav" style="padding-top: 10px;">
            <a href="{% url 'logout' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Sign Out</button>
            </a>
            <a href="{% url 'password_change' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Change Password</button>
            </a>
        </div>
        <p class="navbar-text">디랩의 자랑, {{ user.get_username }}님을 환영합니다.</p>

        {% else %}

        <div class="navbar-nav" style="padding-top: 10px;">
            <a href="{% url 'register' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Sign Up</button>
            </a>
            <a href="{% url 'login' %}">
                <button class="btn btn-sm btn-outline-secondary" type="button">Login</button>
            </a>
        </div>
        <p class="navbar-text">some text</p>
        {% endif %}
    </div>
</nav>


<br><br>
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 logo">


        <div class="thumbnail formCard">
            <h4>새로운 유튜브 북마크를 추가합니다.</h4>
            <p>아래 정보를 정확하게 입력해주세요.</p>
            <br><br>

            <form class="card-text top-buffer" action="." method="post" enctype='multipart/form-data'>
                {% csrf_token %}

                <fieldset class="aligned">
                    <br>
                    <div class="form-group">
                        제목: {{ form.title }}
                    </div>
                    <br>
                    <div class="form-group">
                        주소(URL): <br>
                        - 반드시 /embed/형태로 입력하세요.<br>
                        <div class="well">
                            예)<br>
                            <span class = "codeHighlight">
                                https://www.youtube.com/watch?v=oRzwQrpaA9Q<br>
                                -> https://www.youtube.com<b>/embed/</b>oRzwQrpaA9Q
                            </span>
                        </div>
                        <br>
                        {{ form.url }}
                    </div>
                    <br>
                    <button class="btn btn-primary" type="submit">업로드</button>
                    <br>
                    <br>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="col-sm-2"></div>
</div>


</body>
</html>